### ISSUE TITLE
Include the 'isort' module for sorting the imports according to PEP 8

### ISSUE THREAD

**Issue by snapy666** [myint/pyformat#2]
The [**isort library**](https://github.com/timothycrosley/isort) can sort the imports so that they fully comply with [the import section of PEP 8](https://www.python.org/dev/peps/pep-0008/#imports). ([autopep8](https://github.com/hhatto/autopep8) only does a few changes in regards to imports.)

**Comment by myint** [comment]
Yeah, I'm familiar with it, but I prefer not to add anymore dependencies.

Thanks

**Comment by snapy666** [comment]
@myint Oh.. why not? Wouldn't it be a great addition?
