### ISSUE TITLE
Pyformat does not support docformatter's --blank option

### ISSUE THREAD

**Issue by Zac-HD** [myint/pyformat#9]
Which we need for HypothesisWorks/hypothesis-python#1136.  Do you have any advice on how to handle this, or can we just wait for a pyformat update?

**Comment by myint** [comment]
I think you would need to add such an option to `pyformat`. I personally just use it with the defaults so I haven't run into this.

I'm open to any pull requests to add such options. Thanks!

**Comment by Zac-HD** [comment]
Using defaults works for us too, so no action required :smile:

Thanks for the quick response, and for building such useful software!
